replicaCount: 1
image: gcr.io/google_containers/pause-amd64:3.1

chartreuse:
  enabled: false # In blackbox test, will be enabled
  image:
    repository: dummy-e2e-chartreuse-image
    tag: latest
  alembic:
    username: foo
    password: foo
    database: foo

postgresql:
  image:
    tag: latest
    debug: true
  postgresqlUsername: foo
  postgresqlPassword: foo
  postgresqlDatabase: foo
  postgresqlConfiguration:
    listenAddresses: "'*'"
    fsync: off
    synchronous_commit: off
    full_page_writes: off
  pgHbaConfiguration: |-
    local all all trust
    host all all all trust
  persistence:
    enabled: false
  securityContext:
    enabled: false
  terminationGracePeriodSeconds: 1
