# Only used for e2e tests. Do not use in production.

FROM python:3.12

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN pip install -e .
COPY example/alembic alembic
